# Generated by Django 5.0.6 on 2024-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactions_transation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
