# Generated by Django 5.0.6 on 2024-08-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_options_transactions_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='is_bankrupt',
        ),
    ]
