# Generated by Django 5.0.6 on 2024-08-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactions_is_bankrupt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsBankrupt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
