# Generated by Django 5.0.6 on 2024-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_isbankrupt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsBankrupt',
        ),
    ]
